Repository paulivega/DEV005-burger-queen-api-client, pull requests merged in 2023-06, with the labels that each got.

#11 Login view and router in main
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/assets/img/BQLogo.png
  src/assets/img/FondoBQIpad.png
  src/components/error-page.jsx
  src/components/login.css
  src/components/login.jsx
  src/components/waiter.css
  src/components/waiter.jsx
  src/index.css
  src/main.jsx
Labels: 1 sprint

#12 Function login using fetch and navigate to waiter view working
  package-lock.json
  package.json
  src/components/background.css
  src/components/background.jsx
  src/components/login.jsx
  src/components/waiter.jsx
  src/index.css
Labels: 1 sprint

#37 UPDATE: Login component working for waitress rol
  .eslintrc.cjs
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov-report/src/App.jsx.html
  coverage/lcov-report/src/components/background.jsx.html
  coverage/lcov-report/src/components/error-page.jsx.html
  coverage/lcov-report/src/components/hola.jsx.html
  coverage/lcov-report/src/components/index.html
  coverage/lcov-report/src/components/login.jsx.html
  coverage/lcov-report/src/components/prueba.jsx.html
  coverage/lcov-report/src/components/waiter.jsx.html
  coverage/lcov-report/src/index.html
  coverage/lcov-report/src/main.jsx.html
  coverage/lcov.info
  package-lock.json
  package.json
  setupTest.js
  src/components/login.jsx
  src/components/login.spec.jsx
  src/components/waiter.jsx
  vite.config.js
Labels: sprint 3.

#42 UPDATE: waiter feature with waiter view and btn to send an order to the kitchen
  coverage/base.css
  coverage/block-navigation.js
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/favicon.png
  coverage/index.html
  coverage/lcov-report/index.html
  coverage/lcov-report/src/App.jsx.html
  coverage/lcov-report/src/components/background.jsx.html
  coverage/lcov-report/src/components/error-page.jsx.html
  coverage/lcov-report/src/components/hola.jsx.html
  coverage/lcov-report/src/components/index.html
  coverage/lcov-report/src/components/prueba.jsx.html
  coverage/lcov-report/src/components/waiter.jsx.html
  coverage/lcov-report/src/main.jsx.html
  coverage/lcov.info
  coverage/login.jsx.html
  coverage/prettify.css
  coverage/prettify.js
  coverage/sort-arrow-sprite.png
  coverage/sorter.js
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/assets/img/IconoMeseroP.png
  src/components/background.css
  src/components/button.jsx
  src/components/gralComponents/gralComponents.jsx
  src/components/input.jsx
  src/components/login.jsx
  src/components/waiter.css
  src/components/waiter.jsx
  src/components/waiter/card.jsx
  src/components/waiter/clientName.jsx
  src/components/waiter/navWaiter.jsx
  src/components/waiter/products.jsx
  src/components/waiter/shoppingCart.jsx
  src/components/waiter/shoppingList.jsx
Labels: sprint 4

#43 ADD: chef view with orders pending to cook
  src/assets/img/IconoChef.png
  src/assets/img/IconoOrders.png
  src/components/background.css
  src/components/background.jsx
  src/components/button.jsx
  src/components/chef.css
  src/components/chef.jsx
  src/components/chef/navChef.jsx
  src/components/chef/orderTicket.jsx
  src/components/login.jsx
  src/components/orders/navOrders.jsx
  src/components/status-order.css
  src/components/status-order.jsx
  src/components/waiter.css
  src/components/waiter/products.jsx
  src/index.css
  src/main.jsx
Labels: sprint 4

#44 Merge branch waiter with chef
  src/components/waiter.css
  src/components/waiter.jsx
  src/components/waiter/card.jsx
  src/components/waiter/clientName.jsx
  src/components/waiter/shoppingCart.jsx
Labels: sprint 4

#45 ADD: waiter btn to navigate to orders
  src/assets/img/Orders.png
  src/components/waiter.css
  src/components/waiter/navWaiter.jsx
  src/components/waiter/shoppingCart.jsx
Labels: sprint 4

#63 UPDATE: chef feature with all functionalities
  src/assets/img/Orders.png
  src/components/chef.css
  src/components/chef.jsx
  src/components/chef/orderTicket.jsx
  src/components/status-order.jsx
  src/components/waiter.css
  src/components/waiter.jsx
  src/components/waiter/card.jsx
  src/components/waiter/clientName.jsx
  src/components/waiter/navWaiter.jsx
  src/components/waiter/shoppingCart.jsx
Labels: sprint5
